version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - fiap-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: driver-security-api
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 8080:80
      - 443:443
    networks:
      - fiap-network

networks:
  fiap-network:
    driver: bridge